Prepare directory structure for V1
decentralized-identity/trust-establishment pull request #38
Opened 2022-11-29 01:30 UTC by decentralgabe

2022-11-30 15:53 UTC, dtmcg commented
do you want to keep a working copy under spec/spec.md?

2022-12-01 14:06 UTC, bumblefudge commented
Some thoughts, each of which I'd recommend converting to new issues for addressing post v1 unless they have easy answers or can be addressed by quick edits:
1. why `author` and not, say, `controller`?
2. I took a kind of contrarian, sassy stab at the "todo" to define trust topics, please iterate if it's too sassy or judgmental. Spec is a little cryptic without a little more explanation of its use-case and mental model!
3. The Topic Registry TODO I think should be done before v1.  Since topics are defined as URIs of schemas, you could just point to [schema-directory](https://github.com/decentralized-identity/schema-directory/blob/main/content/schemas.md) or something equivalent at, say, TOIP?  
3B. Sidenote: the schema directory doesn't really look like the [other DIF registries](https://identity.foundation/claim-format-registry/#registry), maybe we can give that group a nudge to make something more... presentable? It feels like another case of the "v1 can't be cut if it depends on a v0 spec or registry" problem that has plagued this WG since time immemorial 😉

2022-12-01 14:19 UTC, bumblefudge commented
also note
![image](https://user-images.githubusercontent.com/37127325/205076155-4aeb7c45-af6a-42d1-a1f9-22aad39a3e80.png)

2022-12-01 14:21 UTC, bumblefudge requested changes

2022-12-01 14:21 UTC, bumblefudge commented on spec/v1/spec.md
> +  The [schema directory](https://github.com/decentralized-identity/schema-directory/blob/main/content/schemas.md) seems like one place where schemas are registered, but I would also recommend adding
This should probably be addressed before v1; see PR discussion for more detail

2022-12-02 18:12 UTC, decentralgabe commented
Thanks @bumblefudge for the review.

I opened up https://github.com/decentralized-identity/schema-directory/issues/5 on the Schema Directory repo.

I've added spec text around Trust Topics that I hope addresses your feedback.

I wonder about the semantic different between _author_ and _controller_. I believe _author_ implies _controller_ -- or at least that is my intention, though I'm not sure the inverse is true. The intent was to establish who created the document.

Got rid of those TODOs. Let me know what you think.

2022-12-02 18:14 UTC, decentralgabe commented on spec/v1/spec.md
> +As per the section on [Publication & Discovery](#publication-discovery) there are a number of possibilities for hosting [[ref:Trust Establishment Documents]]. A related concept is defining a set of w
@csuwildcat let me know what you think about this section, specifically on the accuracy of the DWN text

2022-12-02 18:14 UTC, decentralgabe commented on spec/v1/spec.md
> +::: todo
@TelegramSam could use your magic here

2023-03-13 16:46 UTC, closed without merging